
import { Product, Language } from './types';

export const CATEGORIES = ['All', 'Coffee', 'Tea', 'Bakery', 'Food'];

export const PRODUCTS: Product[] = [
  { id: 'P001', name: 'Espresso', cost: 15000, price: 25000, category: 'Coffee', stock: 100 },
  { id: 'P002', name: 'Latte', cost: 20000, price: 35000, category: 'Coffee', stock: 100 },
  { id: 'P003', name: 'Cappuccino', cost: 20000, price: 35000, category: 'Coffee', stock: 100 },
  { id: 'P004', name: 'Green Tea', cost: 18000, price: 30000, category: 'Tea', stock: 100 },
];

export const TRANSLATIONS: Record<Language, any> = {
  TH: {
    dashboard: 'สรุปผล',
    pos: 'เปิดบิลขาย',
    stock: 'คลังสินค้า',
    reports: 'ประวัติบิล',
    settings: 'ตั้งค่าร้าน',
    total_sales: 'ยอดขายรวม',
    total_bills: 'บิลทั้งหมด',
    cancelled_bills: 'บิลที่ยกเลิก',
    storage: 'พื้นที่ใช้ไป',
    customer: 'ข้อมูลลูกค้า',
    customer_name: 'ชื่อลูกค้า',
    phone: 'เบอร์โทร',
    address: 'ที่อยู่จัดส่ง',
    shipping: 'การขนส่ง',
    payment: 'วิธีชำระเงิน',
    payment_status: 'สถานะเงิน',
    branch: 'สาขาปลายทาง',
    approve: 'อนุมัติและพิมพ์',
    cancel: 'ยกเลิกบิล',
    delete: 'ลบถาวร',
    print: 'พิมพ์บิล',
    total: 'ยอดรวมสุทธิ',
    items: 'รายการสินค้า',
    add_product: 'เพิ่มสินค้า',
    edit_product: 'แก้ไขสินค้า',
    save: 'บันทึกข้อมูล',
    shop_name: 'ชื่อร้านค้า',
    upload_logo: 'อัปโหลดโลโก้',
    receipt: 'ใบเสร็จรับเงิน',
    lang: 'ภาษา',
    stock_qty: 'คงเหลือ',
    price: 'ราคาขาย',
    cost: 'ต้นทุน',
    actions: 'จัดการ',
    clear: 'ล้างตะกร้า',
    discount: 'ส่วนลด',
    import_csv: 'นำเข้าไฟล์ CSV',
    download_template: 'ดาวน์โหลดเทมเพลต',
    id: 'รหัสสินค้า',
    paid: 'จ่ายแล้ว',
    pending: 'ค้างจ่าย',
    transfer: 'โอนเงิน',
    cod: 'COD (เก็บปลายทาง)',
    cash: 'เงินสด',
    anouchit: 'อนุชิต',
    mixay: 'มีไช',
    roung_aloun: 'รุ่งอรุณ',
    pickup: 'รับเอง'
  },
  LA: {
    dashboard: 'ສະຫຼຸບຜົນ',
    pos: 'ເປີດບິນຂາຍ',
    stock: 'ສາງສິນຄ້າ',
    reports: 'ປະຫວັດບິນ',
    settings: 'ຕັ້ງຄ່າຮ້ານ',
    total_sales: 'ຍອດຂາຍລວມ',
    total_bills: 'ບິນທັງໝົດ',
    cancelled_bills: 'ບິນທີ່ຍົກເລີກ',
    storage: 'ພື້ນທີ່ນຳໃຊ້',
    customer: 'ຂໍ້ມູນລູກຄ້າ',
    customer_name: 'ຊື່ລູກຄ້າ',
    phone: 'ເບີໂທ',
    address: 'ທີ່ຢູ່ຈັດສົ່ງ',
    shipping: 'ການຂົນສົ່ງ',
    payment: 'ວິທີຊຳລະເງິນ',
    payment_status: 'ສະຖານະເງິນ',
    branch: 'ສາຂາປາຍທາງ',
    approve: 'ອະນຸມັດແລະພິມ',
    cancel: 'ຍົກເລີກບິນ',
    delete: 'ລົບຖາວອນ',
    print: 'ພິມບິນ',
    total: 'ຍອດລວມສຸດທິ',
    items: 'ລາຍການສິນຄ້າ',
    add_product: 'ເພີ່ມສິນຄ້າໃໝ່',
    edit_product: 'ແກ້ໄຂສິນຄ້າ',
    save: 'ບັນທຶກຂໍ້ມູນ',
    shop_name: 'ຊື່ຮ້ານຄ້າ',
    upload_logo: 'ອັບໂຫລດໂລໂກ້',
    receipt: 'ໃບບິນຮັບເງິນ',
    lang: 'ພາສາ',
    stock_qty: 'ຄົງເຫຼືອ',
    price: 'ລາຄາຂາຍ',
    cost: 'ຕົ້ນທຶນ',
    actions: 'ຈັດການ',
    clear: 'ລ້າງກະຕ່າ',
    discount: 'ສ່ວນຫຼຸດ',
    import_csv: 'ນຳເຂົ້າໄຟລ໌ CSV',
    download_template: 'ດາວໂຫລດເທມເພຼດ',
    id: 'ລະຫັດສິນຄ້າ',
    paid: 'ຈ່າຍແລ້ວ',
    pending: 'ຄ້າງຈ່າຍ',
    transfer: 'ໂອນເງິນ',
    cod: 'COD',
    cash: 'ເງິນສົດ',
    anouchit: 'ອະນຸຊິດ',
    mixay: 'ມີໄຊ',
    roung_aloun: 'ຮຸ່ງອາລຸນ',
    pickup: 'ຮັບເອງ'
  },
  EN: {
    dashboard: 'Dashboard',
    pos: 'POS',
    stock: 'Inventory',
    reports: 'Reports',
    settings: 'Settings',
    total_sales: 'Revenue',
    total_bills: 'Bills',
    cancelled_bills: 'Cancelled',
    storage: 'Storage',
    customer: 'Customer',
    customer_name: 'Customer Name',
    phone: 'Phone',
    address: 'Address',
    shipping: 'Shipping',
    payment: 'Payment',
    payment_status: 'Status',
    branch: 'Branch',
    approve: 'Approve & Print',
    cancel: 'Cancel Bill',
    delete: 'Delete',
    print: 'Print',
    total: 'Total',
    items: 'Items',
    add_product: 'Add Product',
    edit_product: 'Edit Product',
    save: 'Save',
    shop_name: 'Shop Name',
    upload_logo: 'Upload Logo',
    receipt: 'Receipt',
    lang: 'Language',
    stock_qty: 'Stock',
    price: 'Price',
    cost: 'Cost',
    actions: 'Actions',
    clear: 'Clear',
    discount: 'Discount',
    import_csv: 'Import CSV',
    download_template: 'Template',
    id: 'Product ID',
    paid: 'Paid',
    pending: 'Unpaid',
    transfer: 'Transfer',
    cod: 'COD',
    cash: 'Cash',
    anouchit: 'Anouchit',
    mixay: 'Mixay',
    roung_aloun: 'Roung Aloun',
    pickup: 'Pickup'
  }
};
