
import { Product, Language } from './types';

export const CATEGORIES = ['ทั้งหมด', 'กาแฟ', 'ชา', 'เบเกอรี่', 'อาหาร'];

export const PRODUCTS: Product[] = [
  { id: 'P001', code: 'A01', name: 'Espresso Hot', cost: 15000, price: 25000, category: 'กาแฟ', stock: 50 },
  { id: 'P002', code: 'A02', name: 'Latte Ice', cost: 20000, price: 35000, category: 'กาแฟ', stock: 50 },
];

export const TRANSLATIONS: Record<Language, any> = {
  th: {
    dashboard: 'แดชบอร์ด',
    pos: 'ขายสินค้า',
    stock: 'สต็อกสินค้า',
    reports: 'รายงานขาย',
    settings: 'ตั้งค่า',
    promotions: 'โปรโมชั่น',
    total_sales: 'ยอดขายรวม',
    total_profit: 'กำไรสุทธิ',
    stock_value: 'มูลค่าสต็อก',
    top_products: 'สินค้าขายดี',
    top_customers: 'ลูกค้าชั้นนำ',
    cust_name: 'ชื่อลูกค้า',
    cust_phone: 'เบอร์โทรศัพท์',
    cust_address: 'ที่อยู่จัดส่ง',
    cust_branch: 'สาขาปลายทาง',
    shipping: 'การขนส่ง',
    payment_method: 'วิธีชำระเงิน',
    payment_status: 'สถานะการเงิน',
    order_status: 'สถานะออเดอร์',
    bill_discount: 'ส่วนลดท้ายบิล',
    grand_total: 'ยอดชำระสุทธิ',
    clear_cart: 'ล้างตะกร้า',
    checkout: 'ยืนยันการขาย',
    print_receipt: 'พิมพ์ใบเสร็จ',
    cancel_order: 'ยกเลิกออเดอร์',
    download_raw: 'ดาวน์โหลดข้อมูลดิบ',
    download_template: 'ดาวน์โหลดเทมเพลต',
    import_excel: 'นำเข้า Excel',
    delete_all: 'ล้างข้อมูลทั้งหมด',
    inventory_checklist: 'รายการตรวจเช็คสต็อกสินค้า',
    sku_code: 'รหัสสินค้า',
    product_name: 'ชื่อสินค้า',
    system_stock: 'สต็อกในระบบ',
    physical_count: 'จำนวนนับจริง',
    checker_sig: 'ผู้ตรวจนับ',
    manager_sig: 'ผู้อนุมัติ',
    total_items: 'รวมรายการสินค้าทั้งหมด',
    date: 'วันที่',
    store: 'ร้าน',
    theme_choice: 'เลือกสีธีมแบรนด์',
    add_step: 'เพิ่มขั้นบันไดส่วนลด',
    promo_editor: 'จัดการโปรโมชั่น (สูงสุด 10 ขั้น)',
    min_qty: 'ขั้นต่ำ',
    price_per_unit: 'ราคาต่อหน่วย',
    approve: 'อนุมัติบิล',
    edit_details: 'แก้ไขข้อมูล',
    print_bill: 'พิมพ์บิล',
    confirm_approve: 'ยืนยันการอนุมัติบิลนี้?',
    confirm_cancel: 'ต้องการยกเลิกบิลนี้ใช่หรือไม่?',
    bill_management: 'จัดการบิลการขาย',
    status: 'สถานะ'
  },
  lo: {
    dashboard: 'ແດຊບອດ',
    pos: 'ຂາຍສິນຄ້າ',
    stock: 'ສາງສິນຄ້າ',
    reports: 'ລາຍງານການຂາຍ',
    settings: 'ຕັ້ງຄ່າ',
    promotions: 'ໂປຣໂມຊັ່ນ',
    total_sales: 'ຍອດຂາຍລວມ',
    total_profit: 'ກຳໄລສຸດທິ',
    stock_value: 'ມູນຄ່າສາງ',
    top_products: 'ສິນຄ້າຂາຍດີ',
    top_customers: 'ລູກຄ້າຊັ້ນນຳ',
    cust_name: 'ຊື່ລູກຄ້າ',
    cust_phone: 'ເບີໂທລະສັບ',
    cust_address: 'ທີ່ຢູ່ຈັດສົ່ງ',
    cust_branch: 'ສາຂາປາຍທາງ',
    shipping: 'ການຈັດສົ່ງ',
    payment_method: 'ວິທີຊຳລະເງິນ',
    payment_status: 'ສະຖານະການເງິນ',
    order_status: 'ສະຖານະອໍເດີ',
    bill_discount: 'ສ່ວນຫຼຸດທ້າຍບິນ',
    grand_total: 'ຍອດຊຳລະສຸດທິ',
    clear_cart: 'ລ້າງກະຕ່າ',
    checkout: 'ຢືນຢັນການຂາຍ',
    print_receipt: 'ພິມບິນຮັບເງິນ',
    cancel_order: 'ຍົກເລີກອໍເດີ',
    download_raw: 'ດາວໂຫລດຂໍ້ມູນ',
    download_template: 'ດາວໂຫລດເທັມເພລດ',
    import_excel: 'ນຳເຂົ້າ Excel',
    delete_all: 'ລົບຂໍ້ມູນທັງໝົດ',
    inventory_checklist: 'ລາຍການກວດເຊັກສາງສິນຄ້າ',
    sku_code: 'ລະຫັດສິນຄ້າ',
    product_name: 'ຊື່ສິນຄ້າ',
    system_stock: 'ສາງໃນລະບົບ',
    physical_count: 'ຈຳນວນນັບຕົວຈິງ',
    checker_sig: 'ຜູ້ກວດກາ',
    manager_sig: 'ຜູ້ອະນຸມັດ',
    total_items: 'ລວມລາຍການສິນຄ້າທັງໝົດ',
    date: 'ວັນທີ',
    store: 'ຮ້ານ',
    theme_choice: 'ເລືອກສີແບຣນ',
    add_step: 'ເພີ່ມຂັ້ນຕອນສ່ວນຫຼຸດ',
    promo_editor: 'ຈັດການໂປຣໂມຊັ່ນ (ສູງສຸດ 10 ຂັ້ນ)',
    min_qty: 'ຂັ້ນຕ່ຳ',
    price_per_unit: 'ລາຄາຕໍ່ໜ່ວຍ',
    approve: 'ອະນຸມັດບິນ',
    edit_details: 'ແກ້ໄຂຂໍ້ມູນ',
    print_bill: 'ພິມບິນ',
    confirm_approve: 'ຢືນຢັນການອະນຸມັດບິນນີ້?',
    confirm_cancel: 'ຕ້ອງການຍົກເລີກບິນນີ້ແມ່ນບໍ່?',
    bill_management: 'ຈັດການບິນການຂາຍ',
    status: 'ສະຖານະ'
  },
  en: {
    dashboard: 'Dashboard',
    pos: 'Point of Sale',
    stock: 'Inventory',
    reports: 'Sales Report',
    settings: 'Settings',
    promotions: 'Promotions',
    total_sales: 'Total Revenue',
    total_profit: 'Total Profit',
    stock_value: 'Stock Value',
    top_products: 'Top Products',
    top_customers: 'Top Customers',
    cust_name: 'Customer Name',
    cust_phone: 'Phone Number',
    cust_address: 'Shipping Address',
    cust_branch: 'Branch/Dest.',
    shipping: 'Logistics',
    payment_method: 'Payment Method',
    payment_status: 'Payment Status',
    order_status: 'Order Status',
    bill_discount: 'Final Discount',
    grand_total: 'Grand Total',
    clear_cart: 'Clear Cart',
    checkout: 'Process Sale',
    print_receipt: 'Print Receipt',
    cancel_order: 'Cancel Order',
    download_raw: 'Export Raw Data',
    download_template: 'Excel Template',
    import_excel: 'Import Items',
    delete_all: 'Clear All Data',
    inventory_checklist: 'Inventory Checklist',
    sku_code: 'SKU Code',
    product_name: 'Product Name',
    system_stock: 'System Stock',
    physical_count: 'Physical Count',
    checker_sig: 'Checker',
    manager_sig: 'Manager',
    total_items: 'Total Items',
    date: 'Date',
    store: 'Store',
    theme_choice: 'Brand Theme Color',
    add_step: 'Add Discount Step',
    promo_editor: 'Promotion Editor (Max 10 Steps)',
    min_qty: 'Min Qty',
    price_per_unit: 'Price/Unit',
    approve: 'Approve Bill',
    edit_details: 'Edit Info',
    print_bill: 'Print Bill',
    confirm_approve: 'Confirm approval for this bill?',
    confirm_cancel: 'Cancel this bill?',
    bill_management: 'Sale Bill Management',
    status: 'Status'
  }
};
