
import { Product, Language } from './types';

export const CATEGORIES = ['All', 'Coffee', 'Tea', 'Bakery', 'Food'];

export const PRODUCTS: Product[] = [
  { id: 'P001', name: 'Espresso', cost: 15000, price: 25000, category: 'Coffee', stock: 100 },
  { id: 'P002', name: 'Latte', cost: 20000, price: 35000, category: 'Coffee', stock: 100 },
  { id: 'P003', name: 'Cappuccino', cost: 20000, price: 35000, category: 'Coffee', stock: 100 },
  { id: 'P004', name: 'Green Tea', cost: 18000, price: 30000, category: 'Tea', stock: 100 },
];

export const TRANSLATIONS: Record<Language, any> = {
  TH: {
    dashboard: 'สรุปผลประกอบการ',
    pos: 'เปิดบิลขาย',
    stock: 'คลังสินค้า/สต็อก',
    reports: 'ประวัติการขาย',
    settings: 'ตั้งค่าร้านค้า',
    promotions: 'โปรโมชั่น/ราคาพิเศษ',
    total_sales: 'ยอดขายรวม',
    total_profit: 'กำไรสุทธิ',
    stock_value: 'มูลค่าสต็อก',
    total_bills: 'จำนวนบิล',
    customer: 'ข้อมูลลูกค้า',
    customer_name: 'ชื่อลูกค้า',
    phone: 'เบอร์โทรติดต่อ',
    address: 'ที่อยู่จัดส่งสินค้า',
    shipping: 'บริการขนส่ง',
    payment: 'วิธีชำระเงิน',
    payment_status: 'สถานะจ่ายเงิน',
    branch: 'สาขาปลายทาง',
    approve: 'อนุมัติและพิมพ์ใบเสร็จ',
    cancel: 'ยกเลิกบิล',
    delete: 'ลบรายการ',
    print: 'พิมพ์ซ้ำ',
    total: 'ยอดรวมสุทธิ',
    items: 'รายการ',
    add_product: 'เพิ่มสินค้าใหม่',
    edit_product: 'แก้ไขข้อมูลสินค้า',
    save: 'บันทึกการเปลี่ยนแปลง',
    shop_name: 'ชื่อร้านค้า',
    upload_logo: 'อัปโหลดโลโก้ร้าน',
    receipt: 'ใบเสร็จรับเงิน',
    lang: 'ภาษาหลัก',
    stock_qty: 'คงเหลือ',
    price: 'ราคาขาย',
    cost: 'ต้นทุนสินค้า',
    actions: 'จัดการ',
    clear: 'ล้างตะกร้า',
    discount: 'ส่วนลดพิเศษ',
    import_csv: 'นำเข้าไฟล์ CSV',
    id: 'รหัสสินค้า',
    paid: 'ชำระแล้ว',
    pending: 'ยังไม่ชำระ',
    transfer: 'โอนเงิน',
    cod: 'เก็บเงินปลายทาง (COD)',
    cash: 'เงินสด',
    anouchit: 'ขนส่งอนุชิต',
    mixay: 'ขนส่งมีไช',
    roung_aloun: 'ขนส่งรุ่งอรุณ',
    pickup: 'รับที่ร้านเอง',
    profit: 'กำไร',
    order_summary: 'สรุปรายการสั่งซื้อ',
    qty_threshold: 'จำนวนขั้นต่ำ',
    special_price: 'ราคาต่อหน่วยพิเศษ',
    add_tier: 'เพิ่มเกณฑ์ราคา',
    promo_active: 'ใช้ราคาพิเศษแล้ว',
    select_product: 'เลือกสินค้าที่ต้องการทำโปรโมชั่น'
  },
  LA: {
    dashboard: 'ສະຫຼຸບຜົນການຂາຍ',
    pos: 'ເປີດບິນຂາຍ',
    stock: 'ສາງສິນຄ້າ',
    reports: 'ປະຫວັດບິນຂາຍ',
    settings: 'ຕັ້ງຄ່າຮ້ານ',
    promotions: 'ໂປຣໂມຊັ່ນ',
    total_sales: 'ຍອດຂາຍລວມ',
    total_profit: 'ກຳໄລສຸດທິ',
    stock_value: 'ມູນຄ່າສາງ',
    total_bills: 'ຈຳນວນບິນ',
    customer: 'ຂໍ້ມູນລູກຄ້າ',
    customer_name: 'ຊື່ລູກຄ້າ',
    phone: 'ເບີໂທຕິດຕໍ່',
    address: 'ທີ່ຢູ່ຈັດສົ່ງ',
    shipping: 'ການຈັດສົ່ງ',
    payment: 'ວິທີຊຳລະເງິນ',
    payment_status: 'ສະຖານະຊຳລະ',
    branch: 'ສາຂາປາຍທາງ',
    approve: 'ອະນຸມັດແລະພິມບິນ',
    cancel: 'ຍົກເລີກບິນ',
    delete: 'ລົບຖາວອນ',
    print: 'ພິມຄືນ',
    total: 'ຍອດລວມສຸດທິ',
    items: 'ລາຍການ',
    add_product: 'ເພີ່ມສິນຄ້າໃໝ່',
    edit_product: 'ແກ້ໄຂສິນຄ້າ',
    save: 'ບັນທຶກຂໍ້ມູນ',
    shop_name: 'ຊື່ຮ້านຄ້າ',
    upload_logo: 'ອັບໂຫລດໂລໂກ້',
    receipt: 'ໃບບິນຮັບເງິນ',
    lang: 'ພາສາ',
    stock_qty: 'ຄົງເຫຼືອ',
    price: 'ລາຄາຂາຍ',
    cost: 'ຕົ້ນທຶນ',
    actions: 'ຈັດການ',
    clear: 'ລ້າງກະຕ່າ',
    discount: 'ສ່ວນຫຼຸດ',
    import_csv: 'ນຳເຂົ້າ CSV',
    id: 'ລະຫັດສິນຄ້າ',
    paid: 'ຈ່າຍແລ້ວ',
    pending: 'ຄ້າງຈ່າຍ',
    transfer: 'ໂອນເງິນ',
    cod: 'COD (ປາຍທາງ)',
    cash: 'ເງິນສົດ',
    anouchit: 'ຂົນສົ່ງອະນຸຊິດ',
    mixay: 'ຂົນສົ່ງມີໄຊ',
    roung_aloun: 'ຂົນສົ່ງຮຸ່ງອາລຸນ',
    pickup: 'ຮັບເອງ',
    profit: 'ກຳໄລ',
    order_summary: 'ລາຍການສັ່ງຊື້',
    qty_threshold: 'ຈຳນວນຂັ້ນຕ່ຳ',
    special_price: 'ລາຄາພິເສດ',
    add_tier: 'ເພີ່ມເງື່ອນໄຂ',
    promo_active: 'ໃຊ້ລາຄາພິເສດແລ້ວ',
    select_product: 'ເລືອກສິນຄ້າ'
  },
  EN: {
    dashboard: 'Performance',
    pos: 'Sales Terminal',
    stock: 'Inventory',
    reports: 'History',
    settings: 'Store Profile',
    promotions: 'Tiered Pricing',
    total_sales: 'Revenue',
    total_profit: 'Net Profit',
    stock_value: 'Stock Value',
    total_bills: 'Total Orders',
    customer: 'Customer Info',
    customer_name: 'Name',
    phone: 'Phone',
    address: 'Shipping Address',
    shipping: 'Logistic',
    payment: 'Payment',
    payment_status: 'Status',
    branch: 'Branch',
    approve: 'Checkout & Print',
    cancel: 'Void Order',
    delete: 'Remove',
    print: 'Reprint',
    total: 'Total Due',
    items: 'Items',
    add_product: 'Add Product',
    edit_product: 'Edit Product',
    save: 'Save Changes',
    shop_name: 'Store Name',
    upload_logo: 'Brand Logo',
    receipt: 'Official Receipt',
    lang: 'Language',
    stock_qty: 'Qty',
    price: 'Price',
    cost: 'Cost',
    actions: 'Actions',
    clear: 'Clear Cart',
    discount: 'Discount',
    import_csv: 'Import CSV',
    id: 'SKU',
    paid: 'Paid',
    pending: 'Pending',
    transfer: 'Transfer',
    cod: 'COD',
    cash: 'Cash',
    anouchit: 'Anouchit',
    mixay: 'Mixay',
    roung_aloun: 'Roung Aloun',
    pickup: 'Pick Up',
    profit: 'Profit',
    order_summary: 'Summary',
    qty_threshold: 'Min Quantity',
    special_price: 'Promo Unit Price',
    add_tier: 'Add Tier',
    promo_active: 'Promo Price Applied',
    select_product: 'Select Product for Promotion'
  }
};
